### ISSUE TITLE
OJS/OMP 3.4 Compatibility

### ISSUE THREAD

**Issue by busspatrick** [ajnyga/embedHtmlArticleGalley#11]
Hi @ajnyga and @ctgraham ,

I work for the American Theological Library Association (Atla) and we've been using this plugin for years. Recently, I had to modify it in order to to be compatible with OJS 3.4. Would either of you be interested in that code? I'd be happy to push up the changes.

All the best.

**Comment by ajnyga** [comment]
Definitely this would be welcome, thanks!

This is not among the plugins I have maintained actively.

**Comment by busspatrick** [comment]
No worries. I've included the changes in PR #12 .

**Comment by ajnyga** [comment]
Cheers, I have merged you pr and closing this.
