### ISSUE TITLE
getTemplatePath() does not work with OJS 3.1.2

### ISSUE THREAD

**Issue by mpbraendle** [ajnyga/embedHtmlArticleGalley#6]
getTemplatePath() throws a PHP error with OJS 3.1.2. I have made a few refinements so that the plugin works with OJS 3.1.2. Please have a look at https://github.com/mpbraendle/embedHtmlArticleGalley/commit/3ab0b2e127d23652b7de2635ac22f4966f523836 for fixes:

- removed getTemplatePath() completely,
- moved display.tpl to a templates subdirectory
- call display.tpl via getTemplateResource()  (see OJS-67 comment, this is from our internal issue tracking system.
 
EmbedHtmlArticleGalleyPlugin.inc.php is somewhat different to your version because it can handle also incomplete HTML (having no body element) uploaded by the publishers.

Also, I have extended the display.tpl template to display the associated (CC) license with the article text.

Please take over what you would like to.

**Comment by ajnyga** [comment]
thanks! this has been on my todo list, but I am still waiting a while before upgrading our own site to 3.1.2 so have only upgraded the plugins I have in the OJS Plugin gallery for now. 

And a good idea to add the license to the full text view.

I will merge these later today.

**Comment by ajnyga** [comment]
Thanks! I merged everything you had there to master
