### ISSUE TITLE
Statistics and OJS 3.3

### ISSUE THREAD

**Issue by teismann** [ajnyga/embedHtmlArticleGalley#9]
Hi,

Has this plugin been tested with OJS 3.3?
Does the views/download statistics for HTML work with this fix? (We made a fix to remove iframes from the plugin, but unfortunately it also resulted in the HTML views not being collected).

**Comment by ajnyga** [comment]
Thanks, I have not tested with 3.3 yet.

Good find concerning the stats. I think I know what it is about, will have to look into how it could be solved.

**Comment by teismann** [comment]
Sorry for the confusion. We have not yet tested your plugin. The reference above about missing stats was not concerning your plugin, but related to a fix we made ourselves for the PKP HTML Article Galley. That is why we were wondering if you had experienced the same problem?

**Comment by ajnyga** [comment]
Sorry for the delay. Just closing this by saying that I did check the stats back then and they do seem to work with the plugin enabled. I hope you were able to solve your problem.
